services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    plan: free
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: OWNER_ID
        sync: false